### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by LukeVader-IV**
Icons with the correct background one of with is like the original icon and one with the icon used in Nextcloud
https://github.com/vauvenal5/yaga/issues/87

there's a PNG version and an SVG version, The SVG version would be better to implement. And as I understand it, it has to be converted into a "Vector Drawable", This would save a lot of space and make changes to the icon much easier to do.

Some quick searching on the web got me this: https://developer.android.com/studio/write/vector-asset-studio

### CODE REVIEW

**Comment by vauvenal5** [comment]
I am afraid this PR will not work like it is. I assume you did not actually test it?
- Please redirect the target of the PR to the branch **feature/icon**
- If we are allowed to reuse the Photos app icon, why not simply copy it from their repo instead of recreating it? See also my comment in https://github.com/nextcloud/android/issues/8101
- As I mentioned I am using a tool to create the actual icons from the icon parts as required by Android and iOS, it will be necessary to adapt the configuration and test it.

With the PR like it is currently only the icon in the **About** dialog would change and nothing else.

**Comment by vauvenal5** [comment]
The tool I am using for icon generation does not yet support svgs: https://github.com/fluttercommunity/flutter_launcher_icons/issues/20

**Comment by LukeVader-IV** [comment]
1. all right I did
2. i didn't recreate it, i simply used it for the icon and made a foreground layer of it as well for the adaptive icons feature in android, which in this case is just the same icon but with some padding
3. I see, however while they're busy implementing it you could simply use PNG images and have the SVG icons ready for when they finally do implement it (even if this issue has been open for over 3 years)

**Comment by vauvenal5** [comment]
I suggest the following approach. SVG files will be used to track how the icon looks and also for internal uses directly in the app. For the icon generation process we will need additionally two PNG files for the icon generator.

This means we need the following three SVG files:
- foreground.svg (only the foreground part)
- background.svg (only the background color)
- icon.svg (everything together)

We will then create PNG files from them:
- foreground.png
- background.png
- Edit: fastlane/images/icon.png (<-- we will need also a png for the listings in FDroid and the Playstore)
- Edit: fastlane/images/featureGraphic.png (<-- also needs to be reworked)

All the other icons can be deleted. I agree on proceeding with the icon as provided by the Photos app. :+1: 

Edit: Some info for the store graphics:
Icon:
Transparent PNG or JPEG
512 px by 512 px
Up to 1 MB

Feature graphic:
PNG or JPEG
1,024 px by 500 px
Up to 1 MB

**Comment by vauvenal5** [comment]
I will then have to switch to using this lib for in app rendering like in the **About** dialog: https://pub.dev/packages/flutter_svg

Because of this: https://github.com/flutter/flutter/issues/1831

**Comment by vauvenal5** [comment]
Once this is all done we will have a new icon in place :smile:

**Comment by vauvenal5** [comment]
If it is okay for you I will let you clean up the icon files, once this is done I will merge this into the feature branch and do the necessary work to integrate the new images into the generation process and the about dialog.

**Comment by LukeVader-IV** [comment]
hey I'll take care of it, however does the play store not have SVG support?

**Comment by LukeVader-IV** [comment]
I see no way to edit the pull request so I'll simply create a new one

**Pull request closed without merging**
